### ISSUE TITLE
[CHAT]{BUG]: ui-chat is not disconnecting from activity

### ISSUE THREAD

**Issue by sonu-glider** [Azure/communication-ui-library-android#1116]
chatAdapter.disconnect() is not working.

need to stop chat but can't able to its working in background even left from the chat layout.

**Comment by ahammer** [comment]
Thank you for using the Communication UI Library in public preview!

To help us reproduce and triage the issue effectively, could you please provide:

1) What you are observing that indicates the chat is still running in the background.
2) Any relevant logs or additional details.

Your input will help us address this promptly.
 
Best regards,
   Adam Hammer

**Comment by sonu-glider** [comment]
Thank you for responding,

After opening the chat activity getting the log details from server right which is in bulk amount which is in the format of "2024-12-10 12:12:59.216 [#6a894f34-S] T#24894 S.84 [DEBUG4] [httpstack.rt.ConnectionPool] @00007be5c2b01ab0: 6a894f34: " after clicking back button in that activity still these kind of logs getting.

And when I try to use chatAdapter.disconnect() after clicking on back button or during destroy, stop any method i am getting exception like below (I am using these in Kotlin, android studio)


                                                                                                    java.lang.IllegalArgumentException: Builder for class com.azure.android.communication.ui.chat.redux.AppStore Does not exist
                                                                                                      at com.azure.android.communication.ui.chat.presentation.ui.container.ChatCompositeViewImpl.tryPop(ChatCompositeViewImpl.kt:106)
                                                                                                      at com.azure.android.communication.ui.chat.presentation.ui.container.ChatCompositeViewImpl.onDetachedFromWindow(ChatCompositeViewImpl.kt:73)
                                                                                                      at android.view.View.dispatchDetachedFromWindow(View.java:22040)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3984)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3976)
                                                                                                      at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:5563)
                                                                                                      at android.view.ViewRootImpl.doDie(ViewRootImpl.java:8811)
                                                                                                      at android.view.ViewRootImpl.die(ViewRootImpl.java:8787)
                                                                                                      at android.view.WindowManagerGlobal.removeViewLocked(WindowManagerGlobal.java:512)
                                                                                                      at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:453)
                                                                                                      at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:208)
                                                                                                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5670)
                                                                                                      at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
                                                                                                      at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
                                                                                                      at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:180)
                                                                                                      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                      at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                      at android.os.Looper.loop(Looper.java:294)
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:8177)
                                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)


If still having any doubts, then please feel free to reach out.

Best regards,
Sonu Shaik
________________________________

**Comment by ahammer** [comment]
Hi @sonu-glider 

This indicates a bug between the internal state of the chat, and the view component that are displayed.

What is indicated by the logs/code is that when the Chat View is being disconnected (onDetachedFromWindow->tryPop) it needs access to the App Redux State. However, since you've already disposed the ChatAdapter it can no longer locate it via our Service Locator.

The solution to this issue at this time is to ensure that the Chat View's you are using are properly detached/disposed before calling disconnect().

Thank you again for trying the Public Preview of the Azure Communication Services UI Chat Library.

**Comment by ahammer** [comment]
Closing for now. If you continue to have issues, please create a new ticket.
